name: auth_flow
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  shared_preferences: ^0.4.1

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/logo.png